# Generated by Django 3.2 on 2023-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liprary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='liprary/images'),
            preserve_default=False,
        ),
    ]
